# Generated by Django 5.1.6 on 2025-02-14 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rescue_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rescue',
            name='form12A',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='rescue',
            name='form13A',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
    ]
