# Generated by Django 5.1.6 on 2025-02-15 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rescue_app', '0002_rescue_form12a_rescue_form13a'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rescue',
            name='phone',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='rescue',
            name='pincode',
            field=models.CharField(max_length=15),
        ),
    ]
