# Generated by Django 5.1.6 on 2025-02-16 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rescue_app', '0003_alter_rescue_phone_alter_rescue_pincode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rescue',
            old_name='centreName',
            new_name='centerName',
        ),
    ]
